### PR TITLE
Added calendar

### PR DESCRIPTION
**Pull request by Netsujr**
need help implements workout dates

### CODE REVIEW

**Comment by Netsujr** [comment]
TODO - in the morning
implement workout dates,
make calendar smaller
put calendar inside the collapsable

**Comment by alvara** [comment]
> need help implements workout dates

hey @Netsujr , just was experimenting this branches calendar in the dom, i can see how might be doable to select the days to highlight with alot js magic, but im bit worried the resizing issue might be really tricky, doesnt seem to change smoothly unless various other elements are changed at same rate

**Comment by alvara** [comment]
maybe there is some ruby gem we could leverage to do this easier?

**Comment by Netsujr** [comment]
The calendar was done using an old branch. please lets check conflicts together

**Review by david-mambou — APPROVED** [review]

**Pull request merged**
