### PR TITLE
Dashboard

### PR DESCRIPTION
**Pull request by Netsujr**
fixed some routing issues
added the "&'s". which shouldnt break the code but does conflic

### CODE REVIEW

**Comment by Netsujr** [comment]
NOT READY FOR MERGE

**Comment by Netsujr** [comment]
Okay its ready. Will style everything properly tonight!

**Comment by Netsujr** [comment]
Further styling needed tuesday morning (30/11)

**Comment by Netsujr** [comment]
some styling ideas, not sure what to do. research in the morning

**Comment by Netsujr** [comment]
history cate

> some styling ideas, not sure what to do. research in the morning

history categorized by month? we'll see.. we...will....seee.......

**Review by david-mambou — APPROVED** [review]

**Pull request merged**
